version: "3.3"
services:
  db:
    image: mysql:8.0
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_ROOT_PASSWORD: "myrootpassword"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db-data:/var/lib/mysql
    networks:
      - my-network

# Define a custom network for your services
networks:
  my-network:
    driver: bridge

# Define a volume for MySQL data
volumes:
  my-db-data:
